### ISSUE TITLE
签名消息示例运行报错

### ISSUE THREAD

**Issue by brchash** [starcoinorg/starcoin-java#36]
**问题：**
按照 README.md 文档，签名消息的示例运行报错

**环境：** windows、jdk1.8/jdk14

**异常信息：**
```
java.lang.IllegalArgumentException: com.google.common.io.BaseEncoding$DecodingException: Invalid input length 31

	at com.google.common.io.BaseEncoding.decode(BaseEncoding.java:218)
	at org.starcoin.utils.Hex.decode(Hex.java:32)
	at org.starcoin.utils.SignatureUtils.signPersonalMessage(SignatureUtils.java:90)
	at org.starcoin.utils.StarcoinClientSample.testSign(StarcoinClientSample.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
Caused by: com.google.common.io.BaseEncoding$DecodingException: Invalid input length 31
	at com.google.common.io.BaseEncoding$Base16Encoding.decodeTo(BaseEncoding.java:920)
	at com.google.common.io.BaseEncoding.decodeChecked(BaseEncoding.java:233)
	at com.google.common.io.BaseEncoding.decode(BaseEncoding.java:216)
	... 21 more
```

**Comment by cryptoyyxx** [comment]
`    String privateKeyString = "0x587737ebefb4961d377a3ab2f9ceb37b1fa96eb862dfaf954a4a1a99535dfec0";
    String publicKeyString = "0x32ed52d319694aebc5b52e00836e2f7c7d2c7c7791270ede450d21dbc90cbfa1";
    Ed25519PrivateKey privateKey = SignatureUtils.strToPrivateKey(privateKeyString);
    Assert.assertEquals(privateKeyString, Hex.encode(privateKey.value));
    Ed25519PublicKey publicKey = SignatureUtils.getPublicKey(privateKey);
    Assert.assertEquals(publicKeyString, Hex.encode(publicKey.value));
    String message = "Example `personal_sign` message";
    String rst = SignatureUtils.signPersonalMessage(privateKey, message);`

因为我也是第一次阅读 starcoin java 版SDK。所以就按着 `README.md` 文档进行操作。
说明下 issues 反馈的异常，是因为按照以上示例直接运行，导致抛出异常。后面仔细看了下代码，是因为message必须是Hex 字符串，看到代码里面有做Hex.decode 解码(Base16)；message信息是非法的Hex字符串，所以解码时抛出以上异常了。

后面我看到 `SignatureUtilsTest` 测试类中的案例；
`@Test
    public void testSignPersonalMessage() {

        String privateKeyString = "0x94be71d34e32184138cbcad8d24a8deb510aaa74af579f74877b647392421a3f";
        String publicKeyString = "0xa7d45ac5f1d1b5cb1b23303938b6da6b731acff6b05110e2aa0e3c1e677eeb47";
        Ed25519PrivateKey privateKey = SignatureUtils.strToPrivateKey(privateKeyString);
        assertEquals(privateKeyString, Hex.encode(privateKey.value));
        Ed25519PublicKey publicKey = SignatureUtils.getPublicKey(privateKey);
        assertEquals(publicKeyString, Hex.encode(publicKey.value));
        String message = "0568656c6c6f";
        String rst = SignatureUtils.signPersonalMessage(privateKey, message);
        assertEquals(rst, "0xa2c75841ff3bd7d0903a90bba00c5e19a10b0c4434bbdf5dd38f055581f73d1b537808a43045ac7200f6ba7568b0947258477b62e17f09b1a6bc1771c43e1f03");
    }`

`String message = "0568656c6c6f"` 是可以测试通过，该message 通过base16解码后字符串原文内容是 `hello` ；
正常的 `hello` 经过base16 编码后应该是 `68656c6c6f` 。
哈哈哈，不懂就问，那前面为啥加个`05` ？导致解码后是个框框 ``;
于是，我使用正常Base16编码的 `68656c6c6f` 进行消息签名也失败，抛出异常：
`com.novi.serde.DeserializationError: Input is not large enough`

同样，将原文`starcoin` 进行base16编码，得到 `0x73746172636f696e` ，进行签名，也抛出上面的相同异常；

为何正常Base16进行编码的message进行签名，反而不行。
我试着将加个`73746172636f696e` ，例如 `` 变为 `0573746172636f696e` 进行签名。结果也异常了：`com.novi.serde.DeserializationError: Some input bytes were not read`

为何`0568656c6c6f` 又可以？？ 有什么特别？ ？  [黑人问好.jpg]

疑惑的是 这个 签名的message 的规则到底是啥？？  

序列化机制的问题？？

**Comment by qimeila** [comment]
> 
奇怪，我在linux平台并没有出现这个错误，测试通过啊
![Screenshot from 2022-06-03 17-28-29](https://user-images.githubusercontent.com/38450491/171831693-95f4bbcd-cd6c-4160-831a-ba181ed3dec3.png)
