### ISSUE TITLE
部分地址解析resource错误

### ISSUE THREAD

**Issue by ssyuan** [starcoinorg/starcoin-java#41]
com.novi.serde.DeserializationError: Some input bytes were not read
	at org.starcoin.types.AccountAddress.bcsDeserialize(AccountAddress.java:30)
	at org.starcoin.scan.service.TransactionService.getProposalEvents(TransactionService.java:338)
	at org.starcoin.scan.service.TransactionService.getRangeByAddressAll(TransactionService.java:415)
	at org.starcoin.scan.controller.TransactionV2Controller.getRangeByAddressAlias(TransactionV2Controller.java:74)
	at sun.reflect.GeneratedMethodAccessor179.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1063)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:655)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)

**Comment by zlgu** [comment]
关键日志：
![image](https://user-images.githubusercontent.com/5183480/205495505-d2b7da94-805a-4ee4-9912-a1e5915acd03.png)
复现bug：

**Comment by zlgu** [comment]
关键日志：
![image](https://user-images.githubusercontent.com/5183480/205495564-3d4fb156-ebd6-453c-9f67-98ec8f92d087.png)

复现bug：
![image](https://user-images.githubusercontent.com/5183480/205495549-e0861010-c080-4452-b821-8bbb8fbd3543.png)

建议：
starcoinscan-api完善参数格式校验
包括，net，address
如果不做基本格式校验，直接进行es查询，在恶意请求下会造成资源浪费。
同：https://github.com/starcoinorg/starcoin-search/issues/54
